---
- name: "Download archive."
  ansible.builtin.get_url:
    url: "{{ __mattermost_download_url[mattermost_edition] }}"
    checksum: "{{ __mattermost_download_checksum }}"
    dest: "/var/tmp"
    owner: "{{ mattermost_user }}"
    group: "{{ mattermost_group }}"
    mode: "0644"
  register: "__mattermost_downloaded_file"
  notify:
    - "Restart service."

- name: "Ensure directories exist."
  become: true
  ansible.builtin.file:
    path: "{{ item }}"
    state: "directory"
  loop:
    - "{{ mattermost_dir }}"
    - "{{ mattermost_data_dir }}"

- name: "Ensure directories have right permissions."
  ansible.builtin.file:
    path: "{{ item }}"
    state: "directory"
    owner: "{{ mattermost_user }}"
    group: "{{ mattermost_group }}"
    mode: "0750"
  loop:
    - "{{ mattermost_dir }}"
    - "{{ mattermost_data_dir }}"

- name: "Extract archive."
  ansible.builtin.unarchive:
    src: "{{ __mattermost_downloaded_file.dest }}"
    dest: "/var/tmp"
    remote_src: true
    owner: "{{ mattermost_user }}"
    group: "{{ mattermost_group }}"

- name: "Copy archive content."
  ansible.builtin.copy:
    src: "/var/tmp/mattermost/"
    dest: "{{ mattermost_dir }}"
    owner: "{{ mattermost_user }}"
    group: "{{ mattermost_group }}"
    mode: "preserve"
    remote_src: true

- name: "Copy config file."
  ansible.builtin.template:
    src: "config.json.j2"
    dest: "{{ mattermost_dir }}/config/config.json"
    owner: "{{ mattermost_user }}"
    group: "{{ mattermost_group }}"
    mode: "0600"
  notify:
    - "Restart service."

- name: "Fix SELinux context for binaries."
  when: "ansible_facts.selinux.status == 'enabled'"
  block:
    - name: "Change SELinux context of binaries."
      become: true
      community.general.sefcontext:
        ftype: "f"
        path: "{{ mattermost_dir }}/bin/.*"
        setype: "bin_t"
        state: "present"

    - name: "Apply SELinux file context."
      become: true
      ansible.builtin.command:
        cmd: "restorecon -ir {{ mattermost_dir }}/bin"
      changed_when: false
