---
- name: "Import variable tasks."
  ansible.builtin.import_tasks: "set_vars.yml"

- name: "Import preflight tasks."
  ansible.builtin.import_tasks: "preflight.yml"

- name: "Import install tasks."
  ansible.builtin.import_tasks: "install.yml"

- name: "Import systemd tasks."
  ansible.builtin.import_tasks: "systemd.yml"
