---
- name: "Create system group."
  become: true
  ansible.builtin.group:
    name: "{{ mattermost_group }}"
    system: true
    state: "present"

- name: "Create system user."
  become: true
  ansible.builtin.user:
    name: "{{ mattermost_user }}"
    group: "{{ mattermost_group }}"
    system: true
    home: "{{ mattermost_dir }}"
    shell: "/sbin/nologin"
    state: "present"

# - name: "Ensure application directory exists."
#   ansible.builtin.file:
#     path: "{{ mattermost_dir }}"
#     owner: "{{ mattermost_user }}"
#     group: "{{ mattermost_group }}"
#     mode: "0755"
#     state: "directory"
