---
- name: "Setup systemd service."
  ansible.builtin.template:
    src: "mattermost.service.j2"
    dest: "/etc/systemd/system/{{ mattermost_daemon_name }}.service"
    owner: "root"
    group: "root"
    mode: "0644"

- name: "Flush handlers."
  ansible.builtin.meta: "flush_handlers"

- name: "Start and enable service."
  ansible.builtin.systemd_service:
    name: "{{ mattermost_daemon_name }}"
    daemon_reload: true
    enabled: true
    state: "started"
