---
- name: "Setup systemd service."
  ansible.builtin.template:
    src: "mattermost.service.j2"
    dest: "/etc/systemd/system/{{ __mattermost_service_name }}.service"
    owner: "root"
    group: "root"
    mode: "0644"

- name: "Start and enable service."
  ansible.builtin.systemd_service:
    name: "{{ __mattermost_service_name }}"
    daemon_reload: true
    enabled: true
    state: "started"
