---
- name: "Populate service facts."
  ansible.builtin.service_facts: {}

- name: "Stop service."
  when: "mattermost_service_name in ansible_facts.services"
  become: true
  ansible.builtin.service:
    name: "{{ mattermost_service_name }}"
    enabled: false
    state: "stopped"

- name: "Delete files."
  become: true
  ansible.builtin.file:
    path: "{{ item }}"
    state: "absent"
  loop:
    - "/etc/systemd/system/{{ mattermost_service_name }}.service"
    - "{{ mattermost_dir }}"
