---
role_name_check: 1

dependency:
  name: galaxy

driver:
  name: docker

platforms:
  - name: postgres
    image: postgres:15-alpine
    pre_build_image: true
    groups:
      - sidecar
    env:
      POSTGRES_PASSWORD: "mattermost123!"
      POSTGRES_USER: mattermost
      POSTGRES_DB: mattermost
    command: ""
    published_ports:
      - 5432:5432
    networks:
      - name: molecule
  - name: app
    image: "geerlingguy/docker-${MOLECULE_DISTRO:-rockylinux9}-ansible:latest"
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    published_ports:
      - 8065:8065
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    privileged: true
    pre_build_image: true
    networks:
      - name: molecule

provisioner:
  name: ansible
